#!/usr/bin/env bash
cd /home/andrew
curl -O https://dl.google.com/go/go1.11.linux-amd64.tar.gz
sudo tar -C /usr/local -xvzf go1.11.linux-amd64.tar.gz
echo "export GOPATH=$HOME/go" >> ~/.profile
echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.profile
source ~/.profile
go get -v github.com/Lusitaniae/apache_exporter
sudo cp ~/go/bin/apache_exporter /usr/sbin/
touch /etc/systemd/system/apache_exporter.service
sudo cat << EOF > /etc/systemd/system/apache_exporter.service
[Unit]
Description=Apache Exporter

[Service]
User=ubuntu
EnvironmentFile=/etc/sysconfig/apache_exporter
ExecStart=/usr/sbin/apache_exporter $OPTIONS

[Install]
WantedBy=multi-user.target
EOF
sudo mkdir -p /etc/sysconfig
sudo touch /etc/sysconfig/apache_exporter
#sudo cat << EOF > /etc/sysconfig/apache_exporter
#OPTIONS="-scrape_uri='http://127.0.0.1/server-status/?auto'"
#EOF
sudo mv /etc/apache2/mods-enabled/status.conf /etc/apache2/mods-enabled/status.example
touch /etc/apache2/mods-enabled/status.conf
sudo cat << EOF > /etc/apache2/mods-enabled/status.conf
<IfModule mod_status.c>
        # Allow server status reports generated by mod_status,
        # with the URL of http://servername/server-status
        # Uncomment and change the "192.0.2.0/24" to allow access from other hosts.

        <Location /server-status>
                SetHandler server-status
                Require local
                #Require ip 192.0.2.0/24
                Require ip 127.0.0.1/32
        </Location>

        # Keep track of extended status information for each request
        ExtendedStatus On

        # Determine if mod_status displays the first 63 characters of a request or
        # the last 63, assuming the request itself is greater than 63 chars.
        # Default: Off
        #SeeRequestTail On


        <IfModule mod_proxy.c>
                # Show Proxy LoadBalancer status in mod_status
                ProxyStatus On
        </IfModule>


</IfModule>
EOF
match='RewriteRule'
insert='RewriteCond %{REQUEST_URI} !^/server-status/?(.*)'
lms_file='/etc/apache2/sites-available/astria_lms.conf'
sed -i "s/$match/$match\n$insert/" $lms_file

#RewriteCond %{REQUEST_URI} !^/server-status/?(.*)

echo  apache_exporter.service file is created
sudo systemctl daemon-reload
sudo systemctl enable apache_exporter.service
sudo systemctl start apache_exporter
echo  Starting apache exporter...
sudo systemctl status apache_exporter
